apiVersion: v1
kind: ServiceAccount
metadata:
  name: storeit-agent-sa
  namespace: default
  annotations:
    # TODO: Replace with the actual ARN of the IAM role that has Secrets Manager read access
    eks.amazonaws.com/role-arn: arn:aws:iam::461780750771:role/store-it-v2-eks-role
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storeit-agent
  labels:
    app: storeit-agent
spec:
  replicas: 1 # Auto-scalable!
  selector:
    matchLabels:
      app: storeit-agent
  template:
    metadata:
      labels:
        app: storeit-agent
    spec:
      hostNetwork: true
      serviceAccountName: storeit-agent-sa
      containers:
      - name: agent
        image: samarth3282/store-it-v2-agent:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: AWS_REGION
          value: "us-east-1"
        - name: AWS_SECRET_NAME
          value: "store-it-v2/agent"
        - name: USE_SECRETS_MANAGER
          value: "true"
        # The agent needs to know how to reach the backend inside the cluster
        - name: EXPRESS_API_URL
          value: "http://storeit-backend-service.default.svc.cluster.local:80"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: storeit-agent-service
spec:
  type: LoadBalancer # Exposes the agent to the internet via an AWS ALB/ELB
  selector:
    app: storeit-agent
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
