"""
main.py — FastAPI entry point for the StoreIt AI agent.

CHANGES from original:
1. ChatRequest now includes user_token (required) — the user's JWT from the frontend.
2. user_token is set in the ContextVar at the start of each /chat request and
   cleared in the finally block. This scopes the token to each request's async task.
3. CORS is updated to allow the configured frontend + Express backend URLs.
4. A /health endpoint is added that also pings the Express backend.

Streaming behaviour is UNCHANGED — astream_events v1, on_chat_model_stream only.
"""

import os
import json
import httpx
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse
from pydantic import BaseModel

# config.py sets up env and ContextVar — must be imported before agent
from config import EXPRESS_API_URL, user_token_var

from agent import agent_executor
from langchain_core.messages import HumanMessage, AIMessage

# ─── App Setup ────────────────────────────────────────────────────────────────

app = FastAPI(title="StoreIt AI Agent", version="2.0.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://store-it-v2-frontendd.s3-website-us-east-1.amazonaws.com",           # Next.js dev
        "http://98.86.165.219:5000",
        "https://store-it-v2.samarth-patel.dev",           # Express backend (for future server-side calls)
        os.environ.get("FRONTEND_URL", "http://localhost:3000"),
    ],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ─── Request Models ────────────────────────────────────────────────────────────

class ChatRequest(BaseModel):
    message: str
    history: list = []
    user_token: str  # JWT from the frontend — REQUIRED after migration
    # The agent uses this token to authenticate all Express API calls.
    # The frontend must include it with every chat message.


# ─── Endpoints ────────────────────────────────────────────────────────────────

@app.get("/")
def read_root():
    return {"status": "StoreIt AI Agent is running", "version": "2.0.0"}


@app.get("/health")
async def health_check():
    """
    Check agent health + Express backend connectivity.
    Used by Docker health checks and the scripts/check_health.py utility.
    """
    express_ok = False
    try:
        async with httpx.AsyncClient(timeout=5.0) as client:
            r = await client.get(f"{EXPRESS_API_URL}/health")
            express_ok = r.status_code == 200
    except Exception:
        pass

    return {
        "agent": "ok",
        "express_backend": "ok" if express_ok else "unreachable",
        "express_url": EXPRESS_API_URL,
    }


@app.post("/chat")
async def chat_endpoint(request: ChatRequest):
    """
    Streaming chat endpoint.

    Accepts: { message, history, user_token }
    Streams: plain text chunks as they are generated by Gemini.

    The user_token is set in the user_token_var ContextVar before the agent runs,
    making it available to all tool calls within this request's async task tree.
    """
    if not request.user_token:
        raise HTTPException(
            status_code=401,
            detail="user_token is required. The frontend must pass the JWT with each message.",
        )

    try:
        # ── Rebuild conversation history ──────────────────────────────────────
        # The frontend sends prior messages as [{role: "human"|"ai", content: "..."}].
        # We convert them to LangChain message objects so the LLM has full context.
        history_messages = []
        for msg in request.history:
            role = msg.get("role", "") if isinstance(msg, dict) else ""
            content = msg.get("content", "") if isinstance(msg, dict) else ""
            if role == "human":
                history_messages.append(HumanMessage(content=content))
            elif role == "ai":
                history_messages.append(AIMessage(content=content))

        # Append the current user message at the end
        history_messages.append(HumanMessage(content=request.message))

        initial_state = {"messages": history_messages}

        async def event_stream():
            # ── Set user token in ContextVar ─────────────────────────────────────
            # This scopes the JWT to this specific async stream's context.
            token_ctx = user_token_var.set(request.user_token)
            try:
                # astream_events v1 — UNCHANGED from original
                async for event in agent_executor.astream_events(initial_state, version="v1"):
                    kind = event["event"]

                    if kind == "on_chat_model_stream":
                        content = event["data"]["chunk"].content
                        if content:
                            # Handle structured content (list of dict or str) — UNCHANGED
                            if isinstance(content, list):
                                text_parts = []
                                for part in content:
                                    if isinstance(part, dict) and "text" in part:
                                        text_parts.append(part["text"])
                                    elif isinstance(part, str):
                                        text_parts.append(part)
                                content = "".join(text_parts)

                            if isinstance(content, str):
                                yield content
            finally:
                # ── Clear ContextVar ─────────────────────────────────────────
                # Runs after the stream is fully consumed or if the client disconnects.
                user_token_var.reset(token_ctx)

        return StreamingResponse(event_stream(), media_type="text/plain")

    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
